erDiagram
    dim_customers {
        int customer_id PK
        varchar customer_fname
        varchar customer_lname
        varchar customer_email
        varchar customer_segment
        varchar customer_street
        varchar customer_city
        varchar customer_state
        varchar customer_country
        varchar customer_zipcode
        double latitude
        double longitude
    }

    dim_products {
        int product_card_id PK
        varchar product_name
        text product_description
        varchar product_image
        decimal product_price
        int product_status
        int category_id
        varchar category_name
    }

    dim_departments {
        int department_id PK
        varchar department_name
    }

    dim_order_geography {
        int order_geo_id PK
        varchar market
        varchar order_country
        varchar order_region
        varchar order_state
        varchar order_city
        varchar order_zipcode
    }

    fact_order_items {
        int order_item_id PK
        int order_id
        int customer_id FK
        int product_card_id FK
        int department_id FK
        int order_geo_id FK
        timestamp order_date
        timestamp shipping_date
        int days_for_shipping_real
        int days_for_shipment_scheduled
        varchar payment_type
        varchar delivery_status
        varchar order_status
        varchar shipping_mode
        int late_delivery_risk
        decimal benefit_per_order
        decimal sales_per_customer
        decimal order_item_discount
        decimal order_item_discount_rate
        decimal order_item_product_price
        decimal order_item_profit_ratio
        int order_item_quantity
        decimal sales
        decimal order_item_total
        decimal order_profit_per_order
    }

    dim_customers ||--o{ fact_order_items : "składa / FK"
    dim_products ||--o{ fact_order_items : "zawiera / FK"
    dim_departments ||--o{ fact_order_items : "obsługuje / FK"
    dim_order_geography ||--o{ fact_order_items : "miejsce_wysyłki / FK"
